Начальное создание теста
pinchuk8/Lesson_6.1 pull request #1
Opened 2021-12-06 18:41 UTC by pinchuk8

2021-12-13 12:34 UTC, wildpioneer requested changes

2021-12-13 12:34 UTC, wildpioneer commented on src/test/java/tests/Homework1.java
> +       WebElement calculate = driver.findElement(By.cssSelector("input[type = 'button']"));
Придерживайся единообразия форматирования по всему коду

2021-12-13 12:34 UTC, wildpioneer commented on src/test/java/tests/Homework1.java
> +    @Test
Между методами должна быть пуская строка

2021-12-13 12:34 UTC, wildpioneer commented on src/test/java/tests/Homework1.java
> +        //ожидаемые значения
Здесь тоже лучше добавлять пустые строки для разделения блоков

2021-12-13 12:34 UTC, wildpioneer commented on src/test/java/tests/Homework1.java
> +        Thread.sleep(10000);
Для чего здесь ожидание?

2021-12-13 12:34 UTC, wildpioneer commented on src/test/java/tests/Homework1.java
> +        /*Assert.assertEquals(a_board,e_boards,"boards");
Перед отправкой кода на проверку - удаляй закоментированные строки

2021-12-13 12:34 UTC, wildpioneer commented on src/test/java/tests/Homework1.java
> +
В конце метода не оставляй большое количество пустых строк - это создает впечатление, что ты что-то забыла добавить

2021-12-22 13:26 UTC, pinchuk8 commented on src/test/java/tests/Homework1.java
> +       WebElement calculate = driver.findElement(By.cssSelector("input[type = 'button']"));
ок

2021-12-22 13:33 UTC, pinchuk8 commented on src/test/java/tests/Homework1.java
> +    @Test
сделано

2021-12-22 13:33 UTC, pinchuk8 commented on src/test/java/tests/Homework1.java
> +        //ожидаемые значения
сделано

2021-12-22 13:33 UTC, pinchuk8 commented on src/test/java/tests/Homework1.java
> +        Thread.sleep(10000);
убрала

2021-12-22 13:33 UTC, pinchuk8 commented on src/test/java/tests/Homework1.java
> +        /*Assert.assertEquals(a_board,e_boards,"boards");
удалила

2021-12-22 13:34 UTC, pinchuk8 commented on src/test/java/tests/Homework1.java
> +
удалила

2022-01-17 13:06 UTC, closed without merging