Page object simple hw
pinchuk8/Lesson_6.1 pull request #3
Opened 2021-12-18 21:20 UTC by pinchuk8

2021-12-19 19:23 UTC, wildpioneer commented
PR надо было сделать от PageSimple_Object бранч

2021-12-19 19:26 UTC, wildpioneer requested changes

2021-12-19 19:26 UTC, wildpioneer commented on src/test/java/pages/AddProjectPage.java
> +
Лишняя пустая строка

2021-12-19 19:26 UTC, wildpioneer commented on src/test/java/pages/DashboadPage.java
> +    public void add() {
1. Не совсем понимаю смысл метода (не гетера), состоящего всего из одной строки
2. Название метода не отображает его суть

2021-12-22 13:42 UTC, pinchuk8 commented on src/test/java/pages/AddProjectPage.java
> +
убрала

2021-12-22 13:57 UTC, pinchuk8 commented on src/test/java/pages/DashboadPage.java
> +    public void add() {
метод удалила, addProjectTest переделала

2022-01-17 13:02 UTC, closed without merging